require 'slack-stackbot/commands/fortune'
require 'slack-stackbot/commands/search_so'
require 'slack-stackbot/commands/about'
require 'slack-stackbot/commands/help'
require 'slack-stackbot/commands/hi'